### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by tushar8194** [1212050/Shopping-web-Jsp-Servlet#2]
Hi

Just wondering about the admin page. You have css and all the methods implemented but I am unable to find the admin JSP/Servlet.
Have you forgot to commit that part or it's not completed?

Regards

**Comment by manhduydl** [comment]
@tushar8194 
This is small project in school and I can't remember about admin JSP/Servlet. Sorry about that. You can contribute to my project. If you want, I can work with you to complete this task. Thanks for your comment.
Contact with me: manhduydl@gmail.com
